### ISSUE TITLE
希望能支持BAAI/bge-large-zh向量模型？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/langchain-ChatGLM#1012]
如何修改代码支持BAAI/bge-large-zh这个模型？

**Comment by sylcool** [comment]
应该是直接config换就好了吧。
```python
embedding_model_dict = {
    # ...
    "bge-large-zh" : "BAAI/bge-large-zh"
}

# Embedding model name
EMBEDDING_MODEL = "bge-large-zh"
```

**Comment by cristianohello** [comment]
@sylcool 

你测试了吗？这个向量需要加指令提示的

**Comment by zrqssjdys** [comment]
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/60098724/37c9f824-3c5f-46b9-8a67-1e92f422de94)
我按照上图官方的使用方法调用，替换后报错，蹲一个解决办法

**Comment by donttal** [comment]
同样的问题，蹲解决方案

**Comment by liwenju0** [comment]
<img width="636" alt="image" src="https://github.com/chatchat-space/langchain-ChatGLM/assets/16049564/d7a8e632-32bc-4027-86f4-8282123434aa">
instruct 不行，可以用HuggingFaceEmbeddings
prefix 只能自己加了

**Comment by imClumsyPanda** [comment]
已支持

**Comment by banbsyip** [comment]
> 已支持
<img width="1161" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/18277076/bec763a5-9a0d-45df-aec3-e75f24ed62fb">

bge-large-zh-v1.5无法正常建立知识库
