### ISSUE TITLE
[BUG] 启动docker一直显示Waiting for fastchat.serve.model_worker to start up

### ISSUE THREAD

**Issue by zhxchnl** [chatchat-space/langchain-ChatGLM#1032]
**问题描述 / Problem Description**
启动docker 的时候一直在跳Waiting for fastchat.serve.model_worker to start up

Starting fastchat controller...
>> Waiting for fastchat.serve.controller to start up
Starting fastchat model worker...
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up
>> Waiting for fastchat.serve.model_worker to start up

就是跑了这个一行命令 docker run -d -p 80:7860 --gpus all registry.cn-beijing.aliyuncs.com/isafetech/chatmydata:1.0

**Comment by yuqie** [comment]
可以docker exec -it <container id> /bin/bash 进去到/logs/下面查看日志

**Comment by sunuuei** [comment]
遇到了相同的问题，改用sudo docker run之后就ok了。
