### ISSUE TITLE
How to connect the chatglm2-6b model？

### ISSUE THREAD

**Issue by zqszqszqstvt** [chatchat-space/langchain-ChatGLM#1034]
May I ask how to connect to the local model if I simply test simple functions on my own computer? This question is not related to project deployment.

**Comment by zqszqszqstvt** [comment]
How to modify the code：
`args = parser.parse_args(args=['--model', 'fastchat-chatglm-6b', '--no-remote-model', '--load-in-8bit'])

args_dict = vars(args)

shared.loaderCheckPoint = LoaderCheckPoint(args_dict)
torch.cuda.empty_cache()
llm = shared.loaderLLM()`

**Comment by Wu-Fisher** [comment]
shared.loaderLLM() has parameters of “llm_model” and “no_remote_model”, which are your model name and decision of using the local model in your configure file.

**Comment by zqszqszqstvt** [comment]
> shared.loaderLLM() 具有“llm_model”和“no_remote_model”参数，它们是您的模型名称以及在配置文件中使用本地模型的决定。

所以是这样吗，这是我修改后的代码，仍然不能成功链接：`args = parser.parse_args(args=['--model', 'chatglm2-6b', '--no-remote-model', '--load-in-8bit'])

args_dict = vars(args)

shared.loaderCheckPoint = LoaderCheckPoint(args_dict)
torch.cuda.empty_cache()
llm = shared.loaderLLM()
tools = [
    Tool.from_function(
        func=DeepSearch.search,
        name="DeepSearch",
        description=""
    )
]

tool_names = [tool.name for tool in tools]
output_parser = CustomOutputParser()
prompt = CustomPromptTemplate(template=agent_template,
                              tools=tools,
                              input_variables=["related_content","tool_name", "input", "intermediate_steps"])

llm_chain = LLMChain(llm=llm, prompt=prompt)`

**Comment by zqszqszqstvt** [comment]
这是我的报错信息：
`(myenv) (base) root@autodl-container-a5c3118e08-df1ca66d:~/autodl-tmp/langchaindemo# python test.py
INFO  2023-08-11 09:33:42,683-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /root/autodl-tmp/langchaindemo
flagging username: d88dfe8d06f24d749026a0f2f6e25c73

load_model_config /root/autodl-tmp/DB-GPT/models/chatglm2-6b...
Loading /root/autodl-tmp/DB-GPT/models/chatglm2-6b...
INFO  2023-08-11 09:33:43,904-1d: Created a temporary directory at /tmp/tmpi9g2o32l
INFO  2023-08-11 09:33:43,905-1d: Writing /tmp/tmpi9g2o32l/_remote_module_non_scriptable.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:11<00:00,  1.64s/it]
Loaded the model in 17.27 seconds.
Traceback (most recent call last):
  File "test.py", line 52, in <module>
    llm_chain = LLMChain(llm=llm, prompt=prompt)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, generate_prompt, predict, predict_messages (type=type_error)`

**Comment by Wu-Fisher** [comment]
😂其实我的意思是loaderLLM()里面有两个参数，参数改为你[model_config.py](https://github.com/chatchat-space/langchain-ChatGLM/blob/master/configs/model_config.py)文件里面设置好的模型名字，还有路径，其实就可以了

**Comment by zqszqszqstvt** [comment]
> 

model_config.py我已经修改了，但是不知道修改得对不对，如果你有空可以看一下你的代码吗，非常感谢！

**Comment by imClumsyPanda** [comment]
建议更新至最新版代码，该用fastchat的方式加载chatglm2-6b模型
