### ISSUE TITLE
使用baichuan模型时loader 出错

### ISSUE THREAD

**Issue by xxll88** [chatchat-space/langchain-ChatGLM#1043]
File "/userhome/code/langchain-ChatGLM/models/loader/loader.py", line 132, in _load_model
    if LORA_MODEL_PATH_BAICHUAN:
UnboundLocalError: local variable 'LORA_MODEL_PATH_BAICHUAN' referenced before assignmen

在configs.model_config.py 有LORA_MODEL_PATH_BAICHUAN定义，为什么还出错？

**Comment by sylcool** [comment]
同样问题，求解答

**Comment by Peri-albert** [comment]
改一下这个片段成这样，这个版本修改的代码有点问题
if torch.cuda.is_available() and self.llm_device.lower().startswith("cuda"):
    # 根据当前设备GPU数量决定是否进行多卡部署
    num_gpus = torch.cuda.device_count()
    if num_gpus < 2 and self.device_map is None:
        from configs.model_config import LLM_DEVICE, LLM_MODEL, LORA_MODEL_PATH_BAICHUAN
        if LORA_MODEL_PATH_BAICHUAN:
            if LLM_MODEL == "Baichuan-13B-Chat":
                model = AutoModelForCausalLM.from_pretrained(checkpoint, torch_dtype=torch.float16,
                                                             device_map="auto", trust_remote_code=True)
                model.generation_config = GenerationConfig.from_pretrained(checkpoint)
                print("loading lora:{path}".format(path=LORA_MODEL_PATH_BAICHUAN))
                model = PeftModel.from_pretrained(
                    model,
                    LORA_MODEL_PATH_BAICHUAN,
                    torch_dtype=torch.float16,
                    device_map={"": LLM_DEVICE}
                )
                tokenizer = AutoTokenizer.from_pretrained(checkpoint, use_fast=False,
                                                          trust_remote_code=True)
                model.half().cuda()

**Comment by Peri-albert** [comment]
if torch.cuda.is_available() and self.llm_device.lower().startswith("cuda"):
    # 根据当前设备GPU数量决定是否进行多卡部署
    num_gpus = torch.cuda.device_count()
    if num_gpus < 2 and self.device_map is None:
        from configs.model_config import LLM_DEVICE, LLM_MODEL, LORA_MODEL_PATH_BAICHUAN
        if LORA_MODEL_PATH_BAICHUAN:
            if LLM_MODEL == "Baichuan-13B-Chat":
                model = AutoModelForCausalLM.from_pretrained(checkpoint, torch_dtype=torch.float16,
                                                             device_map="auto", trust_remote_code=True)
                model.generation_config = GenerationConfig.from_pretrained(checkpoint)
                print("loading lora:{path}".format(path=LORA_MODEL_PATH_BAICHUAN))
                model = PeftModel.from_pretrained(
                    model,
                    LORA_MODEL_PATH_BAICHUAN,
                    torch_dtype=torch.float16,
                    device_map={"": LLM_DEVICE}
                )
                tokenizer = AutoTokenizer.from_pretrained(checkpoint, use_fast=False,
                                                          trust_remote_code=True)
                model.half().cuda()

**Comment by Peri-albert** [comment]
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/49804947/26c3210f-0bac-4763-a35d-42fd401899a1)

**Comment by qihangf** [comment]
解决了吗

**Comment by xiao1014** [comment]
> 
楼上已经给出答案了
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/13880582/96b0c58d-0c11-4327-b9d4-f0974114af13)

**Comment by imClumsyPanda** [comment]
建议更新至最新版代码，该用fastchat的方式加载baichuan模型
