### ISSUE TITLE
[BUG] Baichuan13B出错UnboundLocalError: local variable 'model' referenced before assignment

### ISSUE THREAD

**Issue by qihangf** [chatchat-space/langchain-ChatGLM#1044]
**问题描述 / Problem Description**
load_model_config /home/wyxx/warBackup/ner/Baichuan-13B/model...
Loading /home/wyxx/warBackup/ner/Baichuan-13B/model...
Traceback (most recent call last):
  File "/home/wyxx/warBackup/ner/langchain-ChatGLM/webui.py", line 334, in <module>
    model_status = init_model()
  File "/home/wyxx/warBackup/ner/langchain-ChatGLM/webui.py", line 106, in init_model
    llm_model_ins = shared.loaderLLM()
  File "/home/wyxx/warBackup/ner/langchain-ChatGLM/models/shared.py", line 39, in loaderLLM
    loaderCheckPoint.reload_model()
  File "/home/wyxx/warBackup/ner/langchain-ChatGLM/models/loader/loader.py", line 506, in reload_model
    self.model, self.tokenizer = self._load_model()
  File "/home/wyxx/warBackup/ner/langchain-ChatGLM/models/loader/loader.py", line 308, in _load_model
    if type(model) is transformers.LlamaForCausalLM:
UnboundLocalError: local variable 'model' referenced before assignment

**Comment by Peri-albert** [comment]
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/49804947/7b9f85a3-0101-4e13-8448-d61a65cca5ca)

**Comment by qihangf** [comment]
我重新git pull了，还是一样的问题。。。

**Comment by Peri-albert** [comment]
自行修改loader.py上述代码至如图所示

**Comment by qihangf** [comment]
> 自行修改loader.py上述代码至如图所示

已经是一样的了啊。。。
或者你后面还改了什么吗
if not any([self.llm_device.lower() == "cpu",
                    self.load_in_8bit, self.is_llamacpp, self.is_chatgmlcpp]):

            if torch.cuda.is_available() and self.llm_device.lower().startswith("cuda"):
                # 根据当前设备GPU数量决定是否进行多卡部署
                num_gpus = torch.cuda.device_count()
                if num_gpus < 2 and self.device_map is None:
                    # if LORA_MODEL_PATH_BAICHUAN is not None:
                    from configs.model_config import LLM_DEVICE, LLM_MODEL, LORA_MODEL_PATH_BAICHUAN
                    if LORA_MODEL_PATH_BAICHUAN:
                        if LLM_MODEL == "Baichuan-13B-Chat":
                            model = AutoModelForCausalLM.from_pretrained(checkpoint, torch_dtype=torch.float16, device_map="auto", trust_remote_code=True, )
                            model.generation_config = GenerationConfig.from_pretrained(checkpoint)
                            print("loading lora:{path}".format(path=LORA_MODEL_PATH_BAICHUAN))
                            model = PeftModel.from_pretrained(
                                    model,
                                    LORA_MODEL_PATH_BAICHUAN,
                                    torch_dtype=torch.float16,
                                    device_map={"": LLM_DEVICE}
                                )
                            tokenizer = AutoTokenizer.from_pretrained(checkpoint, use_fast=False,
                                                                      trust_remote_code=True)
                            model.half().cuda()
                    else:
                        model = (
                            LoaderClass.from_pretrained(checkpoint,
                                                        config=self.model_config,

**Comment by qihangf** [comment]
> 自行修改loader.py上述代码至如图所示

已经是一样的了啊。。。
或者你后面还改了什么吗
if not any([self.llm_device.lower() == "cpu",
                    self.load_in_8bit, self.is_llamacpp, self.is_chatgmlcpp]):

            if torch.cuda.is_available() and self.llm_device.lower().startswith("cuda"):
                # 根据当前设备GPU数量决定是否进行多卡部署
                num_gpus = torch.cuda.device_count()
                if num_gpus < 2 and self.device_map is None:
                    # if LORA_MODEL_PATH_BAICHUAN is not None:
                    from configs.model_config import LLM_DEVICE, LLM_MODEL, LORA_MODEL_PATH_BAICHUAN
                    if LORA_MODEL_PATH_BAICHUAN:
                        if LLM_MODEL == "Baichuan-13B-Chat":
                            model = AutoModelForCausalLM.from_pretrained(checkpoint, torch_dtype=torch.float16, device_map="auto", trust_remote_code=True, )
                            model.generation_config = GenerationConfig.from_pretrained(checkpoint)
                            print("loading lora:{path}".format(path=LORA_MODEL_PATH_BAICHUAN))
                            model = PeftModel.from_pretrained(
                                    model,
                                    LORA_MODEL_PATH_BAICHUAN,
                                    torch_dtype=torch.float16,
                                    device_map={"": LLM_DEVICE}
                                )
                            tokenizer = AutoTokenizer.from_pretrained(checkpoint, use_fast=False,
                                                                      trust_remote_code=True)
                            model.half().cuda()
                    else:
                        model = (
                            LoaderClass.from_pretrained(checkpoint,
                                                        config=self.model_config,

**Comment by imClumsyPanda** [comment]
建议更新至最新版代码，该用fastchat的方式加载baichuan模型

**Comment by imClumsyPanda** [comment]
建议更新至最新版代码，该用fastchat的方式加载baichuan模型

**Comment by baifachuan** [comment]
最新代码，一样的问题
