### ISSUE TITLE
[FEATURE] 能否增加对于milvus向量数据库的支持 / Concise description of the feature

### ISSUE THREAD

**Issue by ColorfulDick** [chatchat-space/langchain-ChatGLM#256]
**功能描述 / Feature Description**
提供一个可选配置，可以让用户自由选择使用faiss本地库或milvus远程/分布式向量数据库，作为向量存储 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
当知识库的数据量大的时候(大于200m的txt文件)，faiss-cpu的io速度太慢，无法使用gpu，且无法横向扩展；而milvus将在2.3版本支持gpu，且是存算分离架构，云原生友好，部署方便； / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
实现一个接口，可以通过配置文件配置使用哪款向量数据库，milvus还是faiss / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
暂无替代方案，目前只调研过milvus / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by shenping1916** [comment]
+1

**Comment by exceedzhang** [comment]
+1

**Comment by fh1999** [comment]
+1

**Comment by Sauloo-huen** [comment]
++1

**Comment by AlexYoung757** [comment]
faiss有gpu版本的，为何这个版本不使用呢

**Comment by AlexYoung757** [comment]
> 

+1，可通过配置，增加常用的向量检索框架，如annoy，faiss以及jina

**Comment by ColorfulDick** [comment]
> faiss有gpu版本的，为何这个版本不使用呢

milvus可是存算分离的，上生产可比faiss猛多了

**Comment by AI-Mart** [comment]
+1

**Comment by AI-Mart** [comment]
什么时候能增加呢？

**Comment by 12xiaoni** [comment]
+1+1+1+1+1

**Comment by MurrayC7** [comment]
+1

**Comment by z5158318** [comment]
milvus和faiss使用方式很像，但是需要docker来启动

**Comment by z5158318** [comment]
new_db = Milvus.from_documents(documents, embedding=embeddings,connection_args={"host": "127.0.0.1", "port": "19530"},)

**Comment by hengwangyue** [comment]
+1

**Comment by Gy1900** [comment]
+1111

**Comment by weifan-zhao** [comment]
+1

**Comment by imClumsyPanda** [comment]
已增加 milvus 和 pg 支持
