### ISSUE TITLE
[FEATURE] 增加对远程向量数据库的支持

### ISSUE THREAD

**Issue by Derrings** [chatchat-space/langchain-ChatGLM#737]
**功能描述**
添加对诸如 Milvus 这类向量数据库的支持，从而能够将向量数据存储在远程的向量数据库中而不是本地的文件系统中。

**解决的问题**
使得项目可以支持分布式、多实例部署，这些实例之间可以共享知识库，也可以集中管理知识库。

**实现建议**
我阅读了项目的大量源码，发现由于项目本身是基于本地文件系统这一前提条件来编写的，因此许多函数的形式参数中加入了 vs_path 这一参数，与本地向量数据库高度绑定。如果要实现此功能，可能的方案如下：
1. 修改 api.py、chains/modules/local_doc_qa.py 文件中的大量函数
2. 设计一个抽象类，将 local_doc_qa.py 中有关向量数据库的操作变为抽象函数，具体逻辑交由实现类完成，提高可扩展性
3. 将基于 Faiss 的本地向量数据库支持全部封装在一个类中，实现上述抽象类，从而完成对现有功能的兼容
4. 添加一个新的配置项，让用户能够选择向量的存储方式

**Comment by Helenailse1** [comment]
期待实现

**Comment by Gy1900** [comment]
+1+1，很希望能早日实现

**Comment by Gy1900** [comment]
@imClumsyPanda 大佬，请问有考虑支持吗

**Comment by bosir** [comment]
期待实现这个功能，当加载的文档多了之后 faiss的性能还是很拉胯的

**Comment by imClumsyPanda** [comment]
已增加 milvus 和 pg_vector 支持
