### ISSUE TITLE
[BUG] 知识库问答时， 答案跟知识库内容无关

### ISSUE THREAD

**Issue by kendou** [chatchat-space/langchain-ChatGLM#814]
**问题描述 / Problem Description**
今天拉取最新文件后（似乎只更新了webui.py一个文件）， 发现知识库问答的结果与知识库中匹配出来的内容毫无关系， 虽然答案下面有“出处”， 但给出的答案只是chatglm2-6b自己的内容。“知识库测试”中可以看到知识库匹配正常， log.csv内容看上去也正常。

**复现问题的步骤 / Steps to Reproduce**
git pull
python3 webui.py

**预期的结果 / Expected Result**
基于知识库的问答

**实际结果 / Actual Result**
答案与知识库无关

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：2d1ad18a4f77cc815f49a16715dae6f7aa5d8143
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: CentOS 7.9
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by ucas010** [comment]
对，有胡说八道的成分，ChatGLM 1和2 都有这种情况。

**Comment by kendou** [comment]
问题是没更新前还是可以的， 明显看到答案是与匹配出来的知识库条目相关性较大的。 更新后， 感觉答案纯粹是从chatglm模型出来的， 和匹配出来的内容毫无关系。

**Comment by ucas010** [comment]
没更新前估计也不太行，可能你的试验次数少。

**Comment by kendou** [comment]
我可能知道原因了： 因为我经常测试同一个问题， Web浏览器的本地Cache起了坏作用。 Chrome切换到隐身模式后， 回答正常了。

所以webui能不能做点小改动， 指示浏览器不要Cache呢？

**Comment by kendou** [comment]
Close.
