### ISSUE TITLE
[BUG] 关于缓存知识库数量CACHED_VS_NUM在model_config.py代码中注释的疑问

### ISSUE THREAD

**Issue by tomFoxxxx** [chatchat-space/langchain-ChatGLM#895]
文件中提到：
`# 缓存知识库数量,如果是ChatGLM2,ChatGLM2-int4,ChatGLM2-int8模型若检索效果不好可以调成’10’`

`CACHED_VS_NUM = 10`

我想表达两个观点：
1.更换ChatGLM2，回答不上的情况确实增加了
2.请问为何提到“_如果是ChatGLM2,ChatGLM2-int4,ChatGLM2-int8模型若检索效果不好可以调成’10’_”？不是很理解这样设置提升效果的原理，实践后也发现并未有提升

**Comment by tomFoxxxx** [comment]
@imClumsyPanda 麻烦大佬解答一下 感谢

**Comment by cristianohello** [comment]
+1
@imClumsyPanda 

麻烦解析一下

**Comment by imClumsyPanda** [comment]
建议前往 https://github.com/chatchat-space/langchain-ChatGLM/pull/768 咨询
