### ISSUE TITLE
接入CHATGLM2-6B效果不错，但是其他模型似乎是不兼容？

### ISSUE THREAD

**Issue by ssbg2** [chatchat-space/langchain-ChatGLM#944]
项目非常牛逼，感谢，给我这种小白一个快速上手的路径。
不过有个疑问，我用 https://huggingface.co/TheBloke/Chinese-Alpaca-33B-SuperHOT-8K-fp16 这个模型，效果就非常差，基本上不能用，然后也一直报错：
'LlamaTokenizerFast' object has no attribute 'add_bos_token'
不知道是不是不兼容？

**Comment by Wu-Fisher** [comment]
我自己使用的体验是自己修改模型load的步骤和新增一个model类对其其它模型的使用，还是比较兼容的。我个人感觉目前给出的models明显glm更新的比较好，其他的还是得自己来做。同时记得改prompt template改成适合自己模型的，用langchain的template可能使用其他模型就会比较差

**Comment by ssbg2** [comment]
> 

感谢，能否再简单举部分代码的例子？
我试过用API这类方案（考虑到能一劳永逸解决不兼容的问题），后面发现效果并不好，现在考虑也准备重写loader和llm了。

**Comment by Wu-Fisher** [comment]
我是在commit c5bc217前修改的，现在是chain为base的model，可能代码参考价值不大。不过核心逻辑修改应该还是models/{llm}/generateAnswer函数和chains/local_doc_qa.py这两部分改的比较重要。（强烈建议改prompt template，其他训练的模型或者垂域微调在其他领域的，一定要对齐他们的prompt，不然效果很差😂

**Comment by ssbg2** [comment]
> 我是在commit c5bc217前修改的，现在是chain为base的model，可能代码参考价值不大。不过核心逻辑修改应该还是models/{llm}/generateAnswer函数和chains/local_doc_qa.py这两部分改的比较重要。（强烈建议改prompt template，其他训练的模型或者垂域微调在其他领域的，一定要对齐他们的prompt，不然效果很差😂

感谢您
