### ISSUE TITLE
gradio网页无法打开

### ISSUE THREAD

**Issue by fxths** [chatchat-space/langchain-ChatGLM#965]
**问题描述 / Problem Description**
运行webui.demo，gradio产生的网址无法打开
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/61527281/8f5c2c20-6115-48c9-b10a-b923b1924b8a)

![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/61527281/bd8a1b97-9740-4737-9d95-c65c0cec5962)

**复现问题的步骤 / Steps to Reproduce**
1. 根据步骤。创建了虚拟环境，并安装了全部依赖；
2. 下载了模型，并修改了config文件中的路径；
3. 之后运行webui.demo，本地的GPU显存中可以看到模型已加载，但是网址打不开。

补充：
本地conda下有两个环境GLM和langchain。GLM曾经成功运行过chatglm2-4bit。langchain即为出现bug版本；
GLM的gradio为3.36.1，langchain的gradio版本为3.37.0。
langchain环境出现bug后，查询过相关问题。发现层有人问过类似问题，基本没有好的解决方案。最可实现的解决方案是降低gradio版本。
我在langchain环境下尝试了讲gradio换成3.21.0版本以及3.36.1版本。发现bug现象是一致的，没有变化

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.1.16
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/61527281/db1a5550-f09e-437a-9aa3-320904d842f8)

- 是否使用 Docker 部署（是/否）：否
- 使用的模型：ChatGLM-6B-4bit
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：text2vec-large-chinese
- 操作系统及版本 / Operating system and version: WSL2 ubuntu22
- Python 版本 / Python version: 3.8.17
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by fxths** [comment]
发现问题了。http://127.0.0.1:7860可以打开。就是功能都是正常的。但是webui里生成的网址是错的。
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/61527281/29ab598d-d991-4928-b6a4-d40a0b0ebc32)
修改了文件里的这里。问题就解决了。

**Comment by kendou** [comment]
代码并没有错， 0.0.0.0表示在本机所有的IP地址上监听7860端口， 但是你访问的时候不能写http://0.0.0.0:7860， 只能指定一个IP地址， 如http://127.0.0.1:7860/, http://localhost:7860/。
你改成127.0.0.1的问题是， 从另一台机器就无法访问webui了。

**Comment by fxths** [comment]
> 代码并没有错， 0.0.0.0表示在本机所有的IP地址上监听7860端口， 但是你访问的时候不能写[http://0.0.0.0:7860，](http://0.0.0.0:7860%EF%BC%8C) 只能指定一个IP地址， 如http://127.0.0.1:7860/, [http://localhost:7860/。](http://localhost:7860/%E3%80%82) 你改成127.0.0.1的问题是， 从另一台机器就无法访问webui了。

谢谢！学到了

**Comment by SkylineYang** [comment]
求助有没有遇到过这种情况
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/86899632/04761de6-b264-4e3b-bf03-173188ab8bd2)
