### ISSUE TITLE
无法通过扫群二维码入群

### ISSUE THREAD

**Issue by queensking** [chatchat-space/langchain-ChatGLM#984]
非常希望能进群学习

**Comment by yansuihehe** [comment]
me too

**Comment by ShellandCore** [comment]
求拉进群

**Comment by xyCaicaicai** [comment]
+1

**Comment by yuangccc** [comment]
微信号lmid_1708，同求拉进群

**Comment by imClumsyPanda** [comment]
已更新二维码

**Comment by yangdatianxia** [comment]
hello，可以拉我一下吗，我扫描也没有进去呀，或者可以把readme得连接给我发一下吗，在master分支得readme得wechat还是二维码过期了

**Comment by imClumsyPanda** [comment]
> hello，可以拉我一下吗，我扫描也没有进去呀，或者可以把readme得连接给我发一下吗，在master分支得readme得wechat还是二维码过期了

二维码已更新

**Comment by yangdatianxia** [comment]
没有呀，现在进群链接变成了404了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/28724448/5a894c8a-46fc-4eaa-ba27-1fe520230443)
