### ISSUE TITLE
[BUG] webui.py 内部错误，无法使用

### ISSUE THREAD

**Issue by wf744** [chatchat-space/langchain-ChatGLM#990]
**问题描述 / Problem Description**
部署完成后，执行webui.py,网页可以打开，但功能无法正常使用，服务器显示内部错误，如下图：

![1](https://github.com/chatchat-space/langchain-ChatGLM/assets/3078907/0bf800a2-aaee-4a46-9e1e-539c6903759f)
![2](https://github.com/chatchat-space/langchain-ChatGLM/assets/3078907/0e6bc066-89f5-43f7-a384-bd60a989b338)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： commit 738
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: win10
- Python 版本 / Python version: Python 3.10.11

**Comment by shnulailai** [comment]
> 经过测试 cli_demo.py 可以正常使用，包括索引文档，回答问题

您好，请问一下输入文件路径有什么需要注意的格式吗？我一直没有成功输入文件过

**Comment by wf744** [comment]
> > 经过测试 cli_demo.py 可以正常使用，包括索引文档，回答问题
> 
> 您好，请问一下输入文件路径有什么需要注意的格式吗？我一直没有成功输入文件过

不能有中文，特殊符号等，不然就会报错

**Comment by si1mon2** [comment]
是不是开了代理？关了代理再部署试试~

**Comment by wf744** [comment]
> > > 是不是开了代理？关了代理再部署试试~
> > 
> > 
> > 厉害，你是怎么想到是这个问题的，我关了代理，重启服务器，就好了。 终于解决了一个问题，谢谢！
> 
> 你的问题我也遇到过 很多人也都遇到过 搜之前的帖子能找到答案

我之前搜索过，没有找到；
