### ISSUE TITLE
[BUG] 为什么加载其他模型很慢，而且回答错误，只有加载chatglm模型很快

### ISSUE THREAD

**Issue by lucheng07082221** [chatchat-space/langchain-ChatGLM#991]
![2023-08-02 14-45-55屏幕截图](https://github.com/chatchat-space/langchain-ChatGLM/assets/3146209/3f8264f3-a77c-40a2-aeb4-7c24c63369f3)

**Comment by imClumsyPanda** [comment]
建议更新至最新版代码，以fastchat方式加载模型，执行效率明显提升。
